main: task4.c funkcijos.c
	gcc -o main task4.c funkcijos.c

.PHONY: programa

programa: main
	main

test: test.c funkcijos.c
	gcc -o test test.c funkcijos.c

.PHONY: testavimas

testavimas: test
	test
